info:
  author:
    name: aoho
  build:
    artifact: "@project.artifactId@"
    name: "@project.name@"
    version: "@project.version@"

server:
  port: 8008

sms:
  retry-limitation-minutes: 1
  validity-minute: 30
  types:
    - register
    - login